{
 "title": "review-api",
 "tags": [
  "nodejs",
  "api",
  "Platform Engineering"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "avg(up{job=\"review-api\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 9, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=\"review-api\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 9, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"review-api.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 9, "y": 6, "w": 9, "h": 6 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"review-api.*\"})"
    }
   ]
  }
 ]
}