apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: review-api
  labels:
    app.kubernetes.io/name: review-api
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
