apiVersion: v1
kind: ServiceAccount
metadata:
  name: review-api
  labels:
    app.kubernetes.io/name: review-api
    finops.ohanyere.io/cost-center: platform-engineering
automountServiceAccountToken: false
